# Assignment: Introduction to Linear Algebra and NumPy

*Objective:*

This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.

# Working with NumPy

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

# Task 1:

Import the numpy library and check its version.

In [2]:
import numpy as np

In [4]:
np.__version__

'2.5.2'

# Creating a NumPy Array:

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

# Task 2:

- Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].


In [ ]:
one_D = np.array([1,2,3,4,5])
print (one_D)

[1 2 3 4 5]


- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.

In [8]:
two_D = np.arange(1, 10).reshape(3, 3)
print(two_D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Generate an array of 10 evenly spaced values between 0 and 5.

In [11]:
array_spaced = np.linspace(0, 5, num = 10)
print(array_spaced)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


# Indexing and Slicing Arrays:

Indexing and slicing allow you to access and modify specific elements of an array.

# Task 3:

- Access the element in the second row, third column of the 2D array you created above.

In [16]:
element = two_D[1, 2]
print(element)

6


- Slice the first two rows and the first two columns from the same array.

In [17]:
slice_array = two_D[:2, :2]
print(slice_array)

[[1 2]
 [4 5]]


- Modify the value in the last row and first column to 100.

In [18]:
two_D[-1, 0] = 100
print(two_D)

[[  1   2   3]
 [  4   5   6]
 [100   8   9]]


# Properties and Methods of NumPy Arrays

NumPy arrays have several useful properties and methods.

# Task 4:

- Find the shape, size, and data type of the 2D array.

In [19]:
array_shape = two_D.shape
array_size = two_D.size
array_dtype = two_D.dtype

print("Shape:", array_shape)
print("Size:", array_size)
print("Data Type:", array_dtype)

Shape: (3, 3)
Size: 9
Data Type: int64


- Change the 1D array into a 2D array of shape (5,1).

In [21]:
one_D = np.array([1, 2, 3, 4, 5])

reshaped_array = one_D.reshape(5, 1)
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]]


- Flatten a multi-dimensional array back into a 1D array.

In [28]:
arry1 = np.random.randint(1, 10, size = (2, 2))
print(arry1)

[[9 6]
 [1 1]]


In [29]:
flattened_array = arry1.flatten()
print(flattened_array)

[9 6 1 1]


# Operations on NumPy Arrays

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

# Task 5:

- Add 5 to every element in the 1D array.

In [33]:
arry2 = np.random.randint(1, 20, size = 5)
arry2

array([14,  2, 11, 10, 13])

In [34]:
adding_E= arry2 + 5

print("Original Array:", arry2)
print("After Adding 5:", adding_E)

Original Array: [14  2 11 10 13]
After Adding 5: [19  7 16 15 18]


- Multiply the 2D array by 3.

In [ ]:
arry3 = np.arange(1, 5).reshape(2, 2)
arry3

array([[1, 2],
       [3, 4]])

In [46]:
multiply_arry3 = arry3 * 3
print("Original Array")
print(arry3)
print("\nAfter Multiplying by 3")
print(multiply_arry3)

Original Array
[[1 2]
 [3 4]]

After Multiplying by 3
[[ 3  6]
 [ 9 12]]


- Perform matrix multiplication between the following two arrays:

A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

In [47]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [50]:
matrix_Multiply = A @ B
print(matrix_Multiply)

[[19 22]
 [43 50]]


# Understanding Broadcasting

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

# Task 6:

Create a 3x3 matrix of ones and a 1D array of length 3.

In [56]:
one_matrix = np.ones(shape = (3, 3), dtype = int)
print(one_matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [61]:
array_1d = np.random.randint(1, 6, size = 3)
print(array_1d)

[1 4 3]


- Add the 1D array to each row of the matrix using broadcasting.

In [62]:
add_1D = one_matrix + array_1d
print(add_1D)

[[2 5 4]
 [2 5 4]
 [2 5 4]]
