In [2]:
import numpy as np

# Elementwise Operations

In [4]:
a = np.array(
    [
        [4,6,8],
        [1,2,4]
    ]
)

b = np.random.randint(1, 45, size = (3,3))
c = np.linspace((0, 5), (60, 100), num = 7)

In [5]:
a

array([[4, 6, 8],
       [1, 2, 4]])

In [6]:
b

array([[26, 30,  3],
       [40, 11,  8],
       [ 7,  8, 10]])

In [7]:
c

array([[  0.        ,   5.        ],
       [ 10.        ,  20.83333333],
       [ 20.        ,  36.66666667],
       [ 30.        ,  52.5       ],
       [ 40.        ,  68.33333333],
       [ 50.        ,  84.16666667],
       [ 60.        , 100.        ]])

solve equation: 4x + 2y = 8 , 5x + 3y =9

In [9]:
A = np.array([[4,2], [5,3]])
B = np.array([8,9])

In [10]:
A_inv = np.linalg.inv(A)

In [13]:
X = np.dot(A_inv, B)
X

array([ 3., -2.])

In [4]:
arr = np.random.randint(0,10, size = (5,4))
arr

array([[4, 4, 2, 3],
       [9, 4, 2, 7],
       [9, 8, 3, 2],
       [3, 6, 9, 1],
       [8, 5, 9, 3]])

In [6]:
arr[2:4, 1:3]

array([[8, 3],
       [6, 9]])

In [7]:
np.random.seed = 99

arr = np.random.randint(0, 10, size = (3, 4, 3))

In [8]:
arr

array([[[7, 0, 1],
        [3, 0, 7],
        [3, 7, 5],
        [8, 2, 4]],

       [[5, 4, 8],
        [3, 8, 3],
        [3, 1, 0],
        [4, 4, 3]],

       [[9, 3, 4],
        [9, 6, 6],
        [3, 7, 4],
        [5, 3, 1]]])

In [10]:
arr[1, -1, 0]

np.int64(4)

In [12]:
arr[::, 1, 1:]

array([[0, 7],
       [8, 3],
       [6, 6]])