In [2]:
import numpy as np

In [2]:
np.__version__

'2.5.2'

# Creating Numpy Array

In [3]:
list1 = [1,2,3,4,5,6,7,8,9]

arry1 = np.array(list1)

In [4]:
arry1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arry1.shape

(9,)

In [6]:
arry1.ndim

1

In [7]:
list2 = [
    [1,2,3] , 
    [4,5,6] , 
    [7,8,9]
]
arry2 = np.array(list2)

In [8]:
arry2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arry2.shape

(3, 3)

In [10]:
arry2.ndim

2

In [11]:
list3 = [
    [
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ],
    [
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ]
]
arry3 = np.array(list3)

In [12]:
arry3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
arry3.shape

(2, 3, 3)

In [14]:
arry3.ndim

3

In [16]:
np.zeros(shape = (2, 3, 6), dtype = int)

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [17]:
np.ones(shape = (2, 3, 6), dtype = int)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [9]:
np.ones(shape = (3, 2, 3, 6), dtype = "int")

array([[[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]]])

In [23]:
np.full(fill_value = 7, shape = (2, 3, 6), dtype = int)

array([[[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]]])

In [24]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
np.linspace((1, 2), (10, 20), num = 4, axis = 1)

array([[ 1.,  4.,  7., 10.],
       [ 2.,  8., 14., 20.]])

In [19]:
np.linspace((0, 1, 2) , (10, 20, 30), num = 5, axis = 0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [40]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.random.randint(0, 50, size = (3, 2, 2)) 

array([[[ 9, 33],
        [ 5, 30]],

       [[17, 48],
        [ 9,  7]],

       [[44, 11],
        [41,  2]]])